<a href="https://colab.research.google.com/github/KateMorf/icev-notebooks/blob/main/1_Pandas%2C_NumPy_e_An%C3%A1lise_de_Dados_com_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introdução a biblioteca Pandas**

In [ ]:
import pandas as pd

import numpy as np

# **Tipos de dados no Pandas**

## **Series**

In [ ]:
# criando Serie com index escificado
notas = pd.Series([12,17,15,20,16], index=["Wilfred", "Abbie", "Harry", "Julia", "Carrie"])
notas

Wilfred    12
Abbie      17
Harry      15
Julia      20
Carrie     16
dtype: int64

In [ ]:
# retornando os valores da Serie
notas.values

array([12, 17, 15, 20, 16])

In [ ]:
# retornando os indexes da Serie
notas.index

Index(['Wilfred', 'Abbie', 'Harry', 'Julia', 'Carrie'], dtype='object')

In [ ]:
# retornando o index 0 da Serie
notas.index[0]

'Wilfred'

In [ ]:
# para verificar o valor associado a um index
notas["Wilfred"]

12

In [ ]:
# para verificar o valor associado a um index
notas.Wilfred

12

In [ ]:
# para verificar o valor associado a um index
notas.values[0]

12

In [ ]:
# visualizar a média e desvio padrão das notas
print("Média:", notas.mean())
print("Desvio padrão:", notas.std())

Média: 16.0
Desvio padrão: 2.9154759474226504


In [ ]:
# descrever brevemente as estatísticas dos dados
notas.describe()

count     5.000000
mean     16.000000
std       2.915476
min      12.000000
25%      15.000000
50%      16.000000
75%      17.000000
max      20.000000
dtype: float64

## **DataFrames**

In [ ]:
# criando um Dataframe
df = pd.DataFrame({'Aluno' : ["Wilfred", "Abbie", "Harry", "Julia", "Carrie"],
                   'Faltas' : [3,4,2,1,4],
                   'Prova' : [2,7,5,10,6],
                   'Seminário': [8.5,7.5,9.0,7.5,8.0]})
df

Aluno  Faltas  Prova  Seminário
0  Wilfred       3      2        8.5
1    Abbie       4      7        7.5
2    Harry       2      5        9.0
3    Julia       1     10        7.5
4   Carrie       4      6        8.0

In [ ]:
# retornar os tipos dos dados de cada coluna do DataFrame
df.dtypes

Aluno         object
Faltas         int64
Prova          int64
Seminário    float64
dtype: object

In [ ]:
# retornar a lista de colunas no DataFrame
df.columns

Index(['Aluno', 'Faltas', 'Prova', 'Seminário'], dtype='object')

In [ ]:
# descrever brevemente as estatísticas dos dados
df.describe()

Faltas      Prova  Seminário
count  5.00000   5.000000    5.00000
mean   2.80000   6.000000    8.10000
std    1.30384   2.915476    0.65192
min    1.00000   2.000000    7.50000
25%    2.00000   5.000000    7.50000
50%    3.00000   6.000000    8.00000
75%    4.00000   7.000000    8.50000
max    4.00000  10.000000    9.00000

In [ ]:
# ordenar o DataFrame pelos valores da coluna Seminário
df.sort_values(by="Seminário")

Aluno  Faltas  Prova  Seminário
1    Abbie       4      7        7.5
3    Julia       1     10        7.5
4   Carrie       4      6        8.0
0  Wilfred       3      2        8.5
2    Harry       2      5        9.0

In [ ]:
# retornar apenas as linhas que possuem Seminário maior que 8.0
df[df['Seminário'] > 8.0]

Aluno  Faltas  Prova  Seminário
0  Wilfred       3      2        8.5
2    Harry       2      5        9.0

In [ ]:
# retornar apenas as linhas que possuem Seminário maior que 8.0 e Prova maior que 3
df[(df["Seminário"] > 8.0) & (df["Prova"] > 3)]

Aluno  Faltas  Prova  Seminário
2  Harry       2      5        9.0

In [ ]:
# retornar apenas as linhas que possuem Seminário maior que 8.0 e Prova maior que 3
# (df.assign(sm = df['Seminário'], pr = df['Prova'])).query('sm > 8.0 & pr > 3')
df.query('Seminário > 8.0 & Prova > 3')

Aluno  Faltas  Prova  Seminário
2  Harry       2      5        9.0

### Diferença entre **.loc[]** e **.iloc[]** resumidamente.
### 1. use .loc [] para retornar dados das rows (linhas) de todas as colunas ou somente das especificadas
### 2. use .iloc [] para retornar posições específicas
### 2.1. passe explicitamente as linhas e colunas, mesmo que seja com ':'

In [ ]:
df.loc[3]

Aluno        Julia
Faltas           1
Prova           10
Seminário      7.5
Name: 3, dtype: object

In [ ]:
df.loc[[3]]

Aluno  Faltas  Prova  Seminário
3  Julia       1     10        7.5

In [ ]:
df.loc[3].to_frame()

3
Aluno      Julia
Faltas         1
Prova         10
Seminário    7.5

In [ ]:
# mostrar apenas as colunas Aluno e Faltas nas posições de index 1, 2 e 3
df.loc[[1,2,3], ['Aluno', 'Faltas']]

Aluno  Faltas
1  Abbie       4
2  Harry       2
3  Julia       1

In [ ]:
print("Aluno", df.iloc[3,0])
print("Faltas", df.iloc[3,1])
print("Prova", df.iloc[3,2])
print("Seminário", df.iloc[3,3])

Aluno Julia
Faltas 1
Prova 10
Seminário 7.5


## **NumPy**

In [ ]:
notas = [10,9,8,7,6,5,4,3,2]
nump_arr = np.array(notas)
nump_arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
nump_arr = np.arange(10,1,-1)
nump_arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
nump_arr = nump_arr.reshape(3,3)
nump_arr

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [ ]:
# somando colunas
nump_arr.sum(axis=0)

array([21, 18, 15])

In [ ]:
# somando linhas
nump_arr.sum(axis=1)

array([27, 18,  9])

In [ ]:
# desvio padrão de cada coluna
nump_arr.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
# desvio padrão de cada linha
nump_arr.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [ ]:
# desvio padrão total
nump_arr.std()

2.581988897471611

# **Aplicando o Pandas em um exemplo de dados**

# **Pandas**

### Lendo um dataset de exemplo

In [ ]:
url = ('https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/tips.csv')
tips = pd.read_csv(url)

### Listar os 5 primeiro registros da tabela.


In [ ]:
tips[['total_bill', 'tip', 'smoker', 'time']].head(5)

total_bill   tip smoker    time
0       16.99  1.01     No  Dinner
1       10.34  1.66     No  Dinner
2       21.01  3.50     No  Dinner
3       23.68  3.31     No  Dinner
4       24.59  3.61     No  Dinner

###Listar as 5 primeiras gorjetas durante o jantar


In [ ]:
tips[tips['time'] == 'Dinner'].head(5)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### OBS.: A instrução acima está simplesmente passando uma série de objetos **True / False** para o DataFrame, retornando todas as linhas com True.


In [ ]:
is_dinner = tips['time'] == 'Dinner'

In [ ]:
is_dinner.value_counts()

True     176
False     68
Name: time, dtype: int64

### LISTAGEM COM MAIS DE UMA CONDIÇÃO**


 #### -- Listar as gorjetas durante os jantares acima de $5.00

##### **PANDAS**

In [ ]:
tips[(tips['time'] == 'Dinner') & (tips['tip'] > 5.00)]

total_bill    tip     sex smoker  day    time  size
23        39.42   7.58    Male     No  Sat  Dinner     4
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
116       29.93   5.07    Male     No  Sun  Dinner     4
155       29.85   5.14  Female     No  Sun  Dinner     5
170       50.81  10.00    Male    Yes  Sat  Dinner     3
172        7.25   5.15    Male    Yes  Sun  Dinner     2
181       23.33   5.65    Male    Yes  Sun  Dinner     2
183       23.17   6.50    Male    Yes  Sun  Dinner     4
211       25.89   5.16    Male    Yes  Sat  Dinner     4
212       48.33   9.00    Male     No  Sat  Dinner     4
214       28.17   6.50  Female    Yes  Sat  Dinner     3
239       29.03   5.92    Male     No  Sat  Dinner     3

#### -- Listar gorjetas de mesas que tiveram pelo menos 5 pessoas jantando ou com total da conta acima de $45

##### **PANDAS**

In [ ]:
tips[(tips['size'] >= 5) | (tips['total_bill'] > 45)]

total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
125       29.80   4.20  Female     No  Thur   Lunch     6
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
185       20.69   5.00    Male     No   Sun  Dinner     5
187       30.46   2.00    Male    Yes   Sun  Dinner     5
212       48.33   9.00    Male     No   Sat  Dinner     4
216       28.15   3.00    Male    Yes   Sat  Dinner     5

### Para checar valores **NULL**, no Pandas utiliza-se os métodos **notna()** ou **isna()**.

In [ ]:
frame = pd.DataFrame({'col1': ['A', 'B', np.NaN, 'C', 'D'],
                      'col2': ['F', np.NaN, 'G', 'H', 'I']})

In [ ]:
frame

col1 col2
0    A    F
1    B  NaN
2  NaN    G
3    C    H
4    D    I

### Suponha que tenhamos uma tabela da mesma estrutura que nosso DataFrame acima. Para ver apenas os registros que são **NULL** na **col2**, fazemos da seguinte maneira:

#### **Pandas**

In [ ]:
 frame[frame['col2'].isna()]

col1 col2
1    B  NaN

### E para ver apenas os registros que não são **NULL** na **col1**, fazemos da seguinte maneira:

#### **Pandas**

In [ ]:
frame[frame['col1'].notna()]

col1 col2
0    A    F
1    B  NaN
3    C    H
4    D    I

### **GROUP BY**

#### **Pandas**

In [ ]:
tips.groupby('sex').size()

sex
Female     87
Male      157
dtype: int64

#### OBS.: Acima utilizamos a função **size()** e não **count()**, porque o **count()** aplica a função em cada coluna retornando o número de registros **not null** em cada uma.


In [ ]:
tips.groupby('sex').count()

total_bill  tip  smoker  day  time  size
sex                                             
Female          87   87      87   87    87    87
Male           157  157     157  157   157   157

#### **MULTIPLAS FUNÇÕES**

##### **PANDAS**

In [ ]:
tips.groupby('day').agg({'tip': np.mean, 'day': np.size})

tip  day
day                
Fri   2.734737   19
Sat   2.993103   87
Sun   3.255132   76
Thur  2.771452   62

##### **GROUP BY MULTIPLAS COLUNAS**

###### Múltiplas funções também podem ser aplicadas de uma só vez. Por exemplo, digamos que gostaríamos de ver como o valor da gorjeta difere por dia da semana - **agg()** permite que você passe um dicionário para o DataFrame agrupado, indicando quais funções aplicar a colunas específicas.

###### **PANDAS**

In [ ]:
tips.groupby(['smoker', 'day']).agg({'tip': [np.size, np.mean]})

tip          
             size      mean
smoker day                 
No     Fri    4.0  2.812500
       Sat   45.0  3.102889
       Sun   57.0  3.167895
       Thur  45.0  2.673778
Yes    Fri   15.0  2.714000
       Sat   42.0  2.875476
       Sun   19.0  3.516842
       Thur  17.0  3.030000

## **JOIN**

### JOINs podem ser executados com **join()** ou **merge()**. Por padrão, **join()** juntará os DataFrames em seus índices. Cada método possui parâmetros que permitem especificar o tipo de junção a ser executada (**LEFT, RIGHT, INNER, FULL**) ou as colunas nas quais participar (column names ou índices).

### Suponha que temos duas tabelas de banco de dados com o mesmo nome e estrutura que nossos DataFrames.

In [ ]:
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'],
                     'value': np.random.randn(4)}) 

df2 = pd.DataFrame({'key': ['B', 'D', 'D', 'E'],
                    'value': np.random.randn(4)})

In [ ]:
df1.head()

key     value
0   A -0.867040
1   B -0.833129
2   C -1.080500
3   D  0.417883

In [ ]:
df2.head()

key     value
0   B -0.475763
1   D -0.542568
2   D -1.178676
3   E  1.705105

#### **PANDAS**

In [ ]:
# merge realiza um INNER JOIN por padrão
pd.merge(df1, df2, on='key')

key   value_x   value_y
0   B -0.833129 -0.475763
1   D  0.417883 -0.542568
2   D  0.417883 -1.178676

#### **merge()** também oferece parâmetros para casos em que você deseja unir a coluna de um DataFrame com os índices de outro DataFrame.

In [ ]:
indexed_df2 = df2.set_index('key')

In [ ]:
indexed_df2

value
key          
B   -0.475763
D   -0.542568
D   -1.178676
E    1.705105

In [ ]:
pd.merge(df1, indexed_df2, left_on='key', right_index=True)

key   value_x   value_y
1   B -0.833129 -0.475763
3   D  0.417883 -0.542568
3   D  0.417883 -1.178676

### **LEFT OUTER JOIN**

#### **PANDAS**

In [ ]:
# show all records from df1
pd.merge(df1, df2, on='key', how='left')

key   value_x   value_y
0   A -0.867040       NaN
1   B -0.833129 -0.475763
2   C -1.080500       NaN
3   D  0.417883 -0.542568
4   D  0.417883 -1.178676

### **RIGHT JOIN**

#### **PANDAS**

In [ ]:
# show all records from df2
pd.merge(df1, df2, on='key', how='right')

key   value_x   value_y
0   B -0.833129 -0.475763
1   D  0.417883 -0.542568
2   D  0.417883 -1.178676
3   E       NaN  1.705105

### **FULL JOIN**

#### **PANDAS**

In [ ]:
# show all records from both frames
pd.merge(df1, df2, on='key', how='outer')

key   value_x   value_y
0   A -0.867040       NaN
1   B -0.833129 -0.475763
2   C -1.080500       NaN
3   D  0.417883 -0.542568
4   D  0.417883 -1.178676
5   E       NaN  1.705105

### **UNION**

#### **UNION ALL** pode ser realizado com a função **concat()** no Pandas.

In [ ]:
df1 = pd.DataFrame({'city': ['Chicago', 'San Francisco', 'New York City'],
                    'rank': range(1, 4)})

In [ ]:
df1

city  rank
0        Chicago     1
1  San Francisco     2
2  New York City     3

In [ ]:
df2 = pd.DataFrame({'city': ['Chicago', 'Boston', 'Los Angeles'],
                    'rank': [1, 4, 5]})

In [ ]:
df2

city  rank
0      Chicago     1
1       Boston     4
2  Los Angeles     5

#### **PANDAS**

In [ ]:
pd.concat([df1, df2])

city  rank
0        Chicago     1
1  San Francisco     2
2  New York City     3
0        Chicago     1
1         Boston     4
2    Los Angeles     5

#### No Pandas podemos fazer a mesma operação combinando o **concat()** com **drop_duplicates()**.

In [ ]:
pd.concat([df1, df2]).drop_duplicates()

city  rank
0        Chicago     1
1  San Francisco     2
2  New York City     3
1         Boston     4
2    Los Angeles     5

## **Funções no Pandas**

### **Top N linhas por grupo**

#### **PANDAS**

In [ ]:
(tips.assign(rn=tips.sort_values(['total_bill'], ascending=False)
                    .groupby(['day'])
                    .cumcount() + 1)
     .query('rn < 3')
     .sort_values(['day', 'rn']))

total_bill    tip     sex smoker   day    time  size  rn
95        40.17   4.73    Male    Yes   Fri  Dinner     4   1
90        28.97   3.00    Male    Yes   Fri  Dinner     2   2
170       50.81  10.00    Male    Yes   Sat  Dinner     3   1
212       48.33   9.00    Male     No   Sat  Dinner     4   2
156       48.17   5.00    Male     No   Sun  Dinner     6   1
182       45.35   3.50    Male    Yes   Sun  Dinner     3   2
197       43.11   5.00  Female    Yes  Thur   Lunch     4   1
142       41.19   5.00    Male     No  Thur   Lunch     5   2

In [ ]:
(tips.assign(rnk=tips.groupby(['day'])['total_bill']
                     .rank(method='first', ascending=False))
     .query('rnk < 3')
     .sort_values(['day', 'rnk']))

total_bill    tip     sex smoker   day    time  size  rnk
95        40.17   4.73    Male    Yes   Fri  Dinner     4  1.0
90        28.97   3.00    Male    Yes   Fri  Dinner     2  2.0
170       50.81  10.00    Male    Yes   Sat  Dinner     3  1.0
212       48.33   9.00    Male     No   Sat  Dinner     4  2.0
156       48.17   5.00    Male     No   Sun  Dinner     6  1.0
182       45.35   3.50    Male    Yes   Sun  Dinner     3  2.0
197       43.11   5.00  Female    Yes  Thur   Lunch     4  1.0
142       41.19   5.00    Male     No  Thur   Lunch     5  2.0

### **UPDATE**

#### **PANDAS**

In [ ]:
tips.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
tips.loc[tips['tip'] < 2, 'tip'] *= 2

In [ ]:
tips.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  2.02  Female     No  Sun  Dinner     2
1       10.34  3.32    Male     No  Sun  Dinner     3

# **ATIVIDADES**

## Exercício 1

Utilizando o dataset Tips, faça a leitura do arquivo em um DataFrame e adicione uma nova coluna booleana que assume valores True se e somente se ** ambos ** dos seguintes forem True:

   * tip maior que 3.
   * sex female.

**Nota:** Ao executar operação lógica **e**, use `&` em vez de `e`.

In [ ]:
import pandas as pd
url = ('https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/tips.csv')
tips = pd.read_csv(url)
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
result = pd.DataFrame({'result': (tips['tip'] > 3.0) & (tips['sex'] == 'Female')})

In [ ]:
tips = pd.concat([tips, result], axis=1)

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size  result
0         16.99  1.01  Female     No   Sun  Dinner     2   False
1         10.34  1.66    Male     No   Sun  Dinner     3   False
2         21.01  3.50    Male     No   Sun  Dinner     3   False
3         23.68  3.31    Male     No   Sun  Dinner     2   False
4         24.59  3.61  Female     No   Sun  Dinner     4    True
..          ...   ...     ...    ...   ...     ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner     3   False
240       27.18  2.00  Female    Yes   Sat  Dinner     2   False
241       22.67  2.00    Male    Yes   Sat  Dinner     2   False
242       17.82  1.75    Male     No   Sat  Dinner     2   False
243       18.78  3.00  Female     No  Thur  Dinner     2   False

[244 rows x 8 columns]

## Exercício 2

Utilizando o dataframe tips criado, faça a indexação do mesmo com o título 'id_tips' e adicione 10% aos valores da coluna total_bill.

In [ ]:
import numpy as np
tips['id_tips'] = pd.DataFrame(np.arange(0, 244))

In [ ]:
tips

In [ ]:
tips.set_index(keys='id_tips', inplace=True)

In [ ]:
tips['total_bill'] = (tips['total_bill'])+(tips['total_bill']*0.10)

In [ ]:
tips

total_bill   tip     sex smoker   day    time  size  result
id_tips                                                             
0            18.689  1.01  Female     No   Sun  Dinner     2   False
1            11.374  1.66    Male     No   Sun  Dinner     3   False
2            23.111  3.50    Male     No   Sun  Dinner     3   False
3            26.048  3.31    Male     No   Sun  Dinner     2   False
4            27.049  3.61  Female     No   Sun  Dinner     4    True
...             ...   ...     ...    ...   ...     ...   ...     ...
239          31.933  5.92    Male     No   Sat  Dinner     3   False
240          29.898  2.00  Female    Yes   Sat  Dinner     2   False
241          24.937  2.00    Male    Yes   Sat  Dinner     2   False
242          19.602  1.75    Male     No   Sat  Dinner     2   False
243          20.658  3.00  Female     No  Thur  Dinner     2   False

[244 rows x 8 columns]